accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from occurrences.models import Occurrence
from . import views

app_name = 'api'

urlpatterns = [
    url(r'^occurrences/$', views.occurrence_list, name='list'),
    url(r'^occurrences/(?P<id>[0-9]+)/$', views.occurrence_details, name='details'),
    url(r'^occurrences/create/$', views.occurrence_create, name='create'),
    url(r'^occurrences/validate/(?P<id>[0-9]+)/$', views.occurrence_update, name='retreive-update'),
    url(r'^occurrences/author/(?P<author>[0-9]+)/$', views.occurrence_by_author, name='occurrence-by-author'),
    url(r'^occurrences/category/(?P<category>[\w]+)/$', views.occurrence_by_category, name='occurrence-by-category'),
    url(r'^occurrences/inrange/$', views.occurrence_in_range, name='occurrence-in-range'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

occurrences/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'occurrences'

urlpatterns = [
    url(r'^$', views.occurrences_list, name="list"),
    url(r'^map/$', views.occurrences_map, name="map"),
    url(r'^create/$', views.occurrence_create, name="create"),
    url(r'^(?P<id>[\d]+)/$', views.occurrence_details, name="detail"),
]

ubi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from occurrences import views as occurrence_views
from accounts import views as accounts_views




urlpatterns = [
    url(r'^$', accounts_views.login_view, name='homepage'), #homepage, list of occurrences
    url(r'^admin/', admin.site.urls, name='admin'), #Administration
    url(r'^api/', include('api.urls'), name='api'), #Rest API
    url(r'^accounts/', include('accounts.urls'), name='accounts'), #Users Management
    url(r'^occurrences/', include('occurrences.urls'), name='occurences'), #Occurrences Management
    url(r'^about/$', views.about, name='about'), #About Page
]


urlpatterns += staticfiles_urlpatterns()

templates/about.html
{% extends 'base_layout.html' %}


{% block content %}

<div class="wrapper">
    <h1>About</h1>
    <p>We like django.</p>
    <p>Administration of Occurrences</p>
</div>

{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Ubi - Occurrences</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />

        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" ></script>
    </head>
    <body>
      <header class="wrapper">
            <h1><a href="{% url 'occurrences:map' %}">Occurrences</a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'occurrences:list' %}">Occurrences</a></li>
                    <li><a href="{% url 'occurrences:map' %}">Show Map</a></li>
                    <li><a href="{% url 'occurrences:create' %}">Create Occurrences</a></li>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>

    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to Occurrences Administration</p>
    </body>
</html>