api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from occurrences.models import Occurrence
from . import views

app_name = 'api'

urlpatterns = [
    url(r'^occurrences/$', views.occurrence_list, name='list'),
    url(r'^occurrences/(?P<id>[0-9]+)/$', views.occurrence_details, name='details'),
    url(r'^occurrences/create/$', views.occurrence_create, name='create'),
    url(r'^occurrences/validate/(?P<id>[0-9]+)/$', views.occurrence_update, name='retreive-update'),
    url(r'^occurrences/author/(?P<author>[0-9]+)/$', views.occurrence_by_author, name='occurrence-by-author'),
    url(r'^occurrences/category/(?P<category>[\w]+)/$', views.occurrence_by_category, name='occurrence-by-category'),
    url(r'^occurrences/inrange/$', views.occurrence_in_range, name='occurrence-in-range'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

occurrences/urls.py
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'occurrences'

urlpatterns = [
    url(r'^$', views.occurrences_list, name="list"),
    url(r'^map/$', views.occurrences_map, name="map"),
    url(r'^create/$', views.occurrence_create, name="create"),
    url(r'^(?P<id>[\d]+)/$', views.occurrence_details, name="detail"),
]

ubi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from occurrences import views as occurrence_views
from accounts import views as accounts_views




urlpatterns = [
    url(r'^$', accounts_views.login_view, name='homepage'), #homepage, list of occurrences
    url(r'^admin/', admin.site.urls, name='admin'), #Administration
    url(r'^api/', include('api.urls'), name='api'), #Rest API
    url(r'^accounts/', include('accounts.urls'), name='accounts'), #Users Management
    url(r'^occurrences/', include('occurrences.urls'), name='occurences'), #Occurrences Management
    url(r'^about/$', views.about, name='about'), #About Page
]


urlpatterns += staticfiles_urlpatterns()

occurrences/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.auth.models import User
from rest_framework.reverse import reverse as api_reverse


class Occurrence(models.Model):
    #All States
    FOR_VALIDATING = 'For Validating'
    VALIDATED ='Validated'
    RESOLVED ='Resolved'

    STATE = (
        (FOR_VALIDATING, 'For Validating'),
        (VALIDATED, 'Validated'),
        (RESOLVED, 'Resolved'),
    )

    #All CATEGORIES
    CONSTRUCTION = 'CONSTRUCTION'
    SPECIAL_EVENT = 'SPECIAL_EVENT'
    INCIDENT = 'INCIDENT'
    WEATHER_CONDITION = 'WEATHER_CONDITION'
    ROAD_CONDITION = 'ROAD_CONDITION'

    CATEGORIES = (
       (CONSTRUCTION, 'planned road work'),
       (SPECIAL_EVENT, 'special events (fair, sport event, etc.)'),
       (INCIDENT, 'accidents and other unexpected events'),
       (WEATHER_CONDITION, 'weather condition affecting the road'),
       (ROAD_CONDITION, 'status of the road that might affect travellers (potholes, bad pavement, etc.)'),
    )

    id = models.AutoField(primary_key=True)
    description = models.CharField(max_length=100)
    location = models.PointField()
    category = models.CharField(max_length=20, choices=CATEGORIES)
    state = models.CharField(max_length=20, choices=STATE, default='For Validating')
    creation_date = models.DateTimeField(auto_now_add=True, editable=False)
    update_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE, editable=False)

    def __str__(self):
        return self.description

    def get_api_url(self, request=None):
        return api_reverse("api:details", kwargs={'id': self.id}, request=request)

occurrences/forms.py
from django.contrib.gis import forms
from . import models


class CreateOccurrence(forms.ModelForm):
    '''
    Form for create an occurrence
    '''
    lat = forms.FloatField(required=True)
    long = forms.FloatField(required=True)
    class Meta:
        model = models.Occurrence
        fields = ('lat', 'long','description', 'category',)

occurrences/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.gis.geos import Point

from .models import Occurrence
from . import forms



@login_required(login_url="/accounts/login")
def occurrences_list(request):
    '''
    View that shows the list of all occurrences order by creation date
    '''
    occurrences = Occurrence.objects.all().order_by('creation_date')
    return render(request, 'occurrences/occurrences_list.html', {'occurrences': occurrences})

@login_required(login_url="/accounts/login")
def occurrence_details(request, id):
    '''
    View that return detail of an occurrence by a given id
    '''
    occurrence = Occurrence.objects.get(id=id)
    return render(request, 'occurrences/occurrence_detail.html', {'occurrence': occurrence})

@login_required(login_url="/accounts/login")
def occurrence_create(request):
    '''
    Create Occurrence View. Only authenticated user.
    '''
    if request.method == 'POST':
        form = forms.CreateOccurrence(request.POST)
        if form.is_valid():
            #save occurence in db
            occurrence = form.save(commit=False)
            lat = form.cleaned_data['lat']
            long = form.cleaned_data['long']
            location = Point(lat,long)
            occurrence.location = location
            occurrence.author = request.user
            occurrence.save()
            return redirect('occurrences:list')
    else:
        form = forms.CreateOccurrence()
    return render(request, 'occurrences/occurrence_create.html', {'form':form})

@login_required(login_url="/accounts/login")
def occurrences_map(request):
    '''
    View that shows the list of all occurrences in a map
    '''
    occurrences = Occurrence.objects.all()
    return render(request, 'occurrences/occurrences_map.html', {'occurrences': occurrences})

occurrences/templates/occurrences/occurrence_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create-occurrence">
  <h2>Create an Occurrence</h2>
  <form class="site-form" action="{% url 'occurrences:create' %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="create">
  </form>
</div>

{% endblock %}

occurrences/templates/occurrences/occurrence_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="occurrence-detail">
    <div class="occurrence">
      <h2>{{ occurrence.description }}</h2>
      <p><strong>Category:</strong>{{ occurrence.get_category_display }}</p>
      <p><strong>State:</strong> {{ occurrence.state }}</p>
      <br />
      <p><strong>By:</strong> {{ occurrence.author }}</p>
      <p><strong>Create on:</strong> {{ occurrence.creation_date }}</p>
      <p><strong>Updated on:</strong> {{ occurrence.update_date }}</p>
    </div>
</div>

{% endblock %}

occurrences/templates/occurrences/occurrences_list.html
{% extends 'base_layout.html' %}

{% block content %}

 <div id="tableList">
   <table id="myTable" class="display" style="width:100%">
           <thead>
               <tr>
                   <th>Descryption</th>
                   <th>Category</th>
                   <th>State</th>
                   <th>location</th>
                   <th>Creation date</th>
                   <th>Author</th>
               </tr>
           </thead>
           <tbody>
             {% for occurrence in occurrences %}
               <tr>
                   <td>{{ occurrence.description }}</td>
                   <td>{{ occurrence.get_category_display }}</td>
                   <td>{{ occurrence.state }}</td>
                   <td>({{ occurrence.location.x }},{{ occurrence.location.y }})</td>
                   <td>{{ occurrence.creation_date }}</td>
                   <td>{{ occurrence.author }}</td>
               </tr>
              {% endfor %}

           </tbody>
       </table>
 </div>

<script>

  $(document).ready( function () {
      $('#myTable').DataTable();
  } );

</script>

{% endblock %}

occurrences/templates/occurrences/occurrences_map.html
{% extends 'base_layout.html' %}

{% block content %}

 <div id="googleMap" style="width:100%;height:400px;"></div>

 <script>

 // create map
 function myMap() {
   var mapProp= {
       center:new google.maps.LatLng(51.508742,-0.120850),
       zoom:2,
   };

   var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);


   {% for occurrence in occurrences %}
     {% if occurrence.state == 'Resolved' or occurrence.state == 'Validated' %}

        _{{occurrence.id}} = new google.maps.Marker({
           map: map,
           animation: google.maps.Animation.DROP,
           position: {lat: {{occurrence.location.x}}, lng: {{occurrence.location.y}}},
           // label: '{{occurrence.state}}',
           title: '{{occurrence.author.username}}'
         });

         var contentString = '<div id="content">'+
             '<div id="">'+
             '</div>'+
             '<h1 id="firstHeading" class="firstHeading">{{occurrence.description}}</h1>'+
             '<div id="bodyContent">'+
             '<p><b>Category:</b> {{occurrence.get_category_display}} </p>'+
             '<p><b>State:</b> {{occurrence.state}} </p>'+
             '<p><b>Created on:</b> {{occurrence.creation_date}} </p>'+
             '<p><b>Author: {{occurrence.author.username}}</b>, (last update: {{occurrence.update_date}}).</p>'+
             '</div>'+
             '</div>';

         var infowindow_{{occurrence.id}} = new google.maps.InfoWindow({
           content: contentString
         });

         _{{occurrence.id}}.addListener('click', function() {
             infowindow_{{occurrence.id}}.open(map, _{{occurrence.id}});
           });

      {% endif %}

      {% if occurrence.state == 'For Validating' and occurrence.author == user %}

          _{{occurrence.id}} = new google.maps.Marker({
             map: map,
             icon: 'https://maps.google.com/mapfiles/ms/icons/green-dot.png',
             animation: google.maps.Animation.DROP,
             position: {lat: {{occurrence.location.x}}, lng: {{occurrence.location.y}}},
             title: '{{occurrence.author.username}}'
             // icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'
           });

           var contentString = '<div id="content">'+
               '<div id="">'+
               '</div>'+
               '<h1 id="firstHeading" class="firstHeading">{{occurrence.description}}</h1>'+
               '<div id="bodyContent">'+
               '<p><b>Category:</b> {{occurrence.get_category_display}} </p>'+
               '<p><b>State:</b> {{occurrence.state}} </p>'+
               '<p><b>Created on:</b> {{occurrence.creation_date}} </p>'+
               '<p><b>Author: {{occurrence.author.username}}</b>, (last update: {{occurrence.update_date}}).</p>'+
               '</div>'+
               '</div>';

           var infowindow_{{occurrence.id}} = new google.maps.InfoWindow({
             content: contentString
           });

           _{{occurrence.id}}.addListener('click', function() {
               infowindow_{{occurrence.id}}.open(map, _{{occurrence.id}});
             });

      {% endif %}


   {% endfor %}


  }
 </script>

 <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfJdkQvwhB31GMWGE3eIi8l64Q7tRMTg4&callback=myMap"></script>


{% endblock %}